const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({channel:process.env.LAB4NET_BROWSER_CHANNEL||undefined});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);
 async function columns(){const r={};for(const id of ['brief','checkWin','mapPanel','console'])r[id]=await page.locator('#'+id).boundingBox();const a=r.brief,b=r.checkWin,c=r.mapPanel,d=r.console;assert.ok(a.x+a.width<b.x&&b.x+b.width<c.x);assert.ok(Math.abs(a.y-b.y)<2&&Math.abs(a.y-c.y)<2);assert.ok(Math.abs(a.height-b.height)<2);assert.ok(Math.abs(c.height-d.height)<2);assert.ok(Math.abs(c.x-d.x)<2&&Math.abs(c.width-d.width)<2);assert.ok(c.y+c.height<d.y);assert.ok(Math.abs(a.y+a.height-d.y-d.height)<2);const m=await page.locator('main').boundingBox();assert.ok(a.height>m.height*.9);assert.ok(d.x+d.width<=page.viewportSize().width+1);return r;}
 await columns();await page.locator('#layouts').click();assert.ok(await page.locator('[data-layout="columns"]').isVisible());await page.locator('[data-layout="balanced"]').click();const old=await page.evaluate(()=>localStorage.getItem('lab4net-layout-v2'));await page.reload();assert.equal(await page.evaluate(()=>localStorage.getItem('lab4net-layout-v2')),old,'existing arrangement preserved');
 await page.locator('#guidePopBtn').click();assert.ok(await page.locator('#guideWin').isVisible());await page.locator('#layouts').click();await page.locator('[data-layout="columns"]').click();assert.ok(!(await page.locator('#guideWin').isVisible()));await columns();await page.locator('#undoLayout').click();assert.ok(await page.locator('#guideWin').isVisible());
 await page.locator('#resetLayout').click();await columns();assert.ok(!(await page.locator('#guideWin').isVisible()));await page.reload();await columns();
 // The divider between Mission and Tasks grows Mission without changing the right stack.
 let r=await columns();await page.mouse.move(r.brief.x+r.brief.width-2,r.brief.y+150);await page.mouse.down();await page.mouse.move(r.brief.x+r.brief.width+38,r.brief.y+150,{steps:5});await page.mouse.up();let resized=await columns();assert.ok(resized.brief.width>r.brief.width+25);assert.ok(Math.abs(resized.mapPanel.x-r.mapPanel.x)<2);await page.locator('#undoLayout').click();await columns();
 for(const [width,height]of [[1920,1080],[1366,768],[1024,768]]){await page.setViewportSize({width,height});await page.locator('#resetLayout').click();await columns();}
 await page.setViewportSize({width:1440,height:1000});await page.locator('#resetLayout').click();if(process.env.LAB4NET_SCREENSHOTS){fs.mkdirSync(process.env.LAB4NET_SCREENSHOTS,{recursive:true});await page.locator('#notice').click().catch(()=>{});await page.waitForTimeout(300);await page.screenshot({path:path.join(process.env.LAB4NET_SCREENSHOTS,'tall-columns.png')});}
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('#brief').isVisible());await page.locator('#networkView').click();assert.ok(await page.locator('#console').isVisible());assert.deepEqual(errors,[]);console.log('PASS tall columns: two full-height left panels, equal right stack, fresh default, preserve existing layouts, preset/reset/reload, guide docking/undo, shared divider, three desktop sizes and phone/reduced motion.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
