const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({channel:process.env.LAB4NET_BROWSER_CHANNEL||undefined});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);
 const rects=()=>page.evaluate(()=>Object.fromEntries(['brief','checkWin','mapPanel','console','practice','guideWin'].filter(id=>document.getElementById(id).getClientRects().length).map(id=>{const r=document.getElementById(id).getBoundingClientRect();return [id,{x:r.x,y:r.y,w:r.width,h:r.height}];})));
 const same=(a,b)=>{for(const id of Object.keys(a))for(const k of ['x','y','w','h'])assert.ok(Math.abs(a[id][k]-b[id][k])<2,`${id}.${k} unchanged`);};
 async function tiled(){const p=await rects(),v=Object.entries(p),size=page.viewportSize();for(const [id,r]of v)assert.ok(r.x>=0&&r.y>=0&&r.w>100&&r.h>90&&r.x+r.w<=size.width+1&&r.y+r.h<=size.height+1,`${id} fits`);for(let i=0;i<v.length;i++)for(let j=i+1;j<v.length;j++){const [a,p]=v[i],[b,q]=v[j];assert.ok(Math.min(p.x+p.w,q.x+q.w)-Math.max(p.x,q.x)<1||Math.min(p.y+p.h,q.y+q.h)-Math.max(p.y,q.y)<1,`${a}/${b} non-overlap`);}return p;}
 async function preset(id='balanced'){await page.locator('#layouts').click();await page.locator(`[data-layout="${id}"]`).click();return tiled();}
 async function begin(id){const r=await page.locator('#'+id).boundingBox();await page.mouse.move(r.x+70,r.y+20);await page.mouse.down();await page.mouse.move(r.x+90,r.y+45,{steps:4});}
 async function target(id,side){const b=await page.locator(`.dock-target[data-target="${id}"][data-side="${side}"]`).boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:6});}
 // Real rendered sizes must follow saved geometry, not the old sidebar's 43% cap.
 let before=await preset(),r=before.brief,m=await page.locator('main').boundingBox();assert.equal(await page.locator('#brief').evaluate(el=>getComputedStyle(el).maxHeight),'none');
 await page.mouse.move(r.x+r.w/2,r.y+r.h-2);await page.mouse.down();await page.mouse.move(r.x+r.w/2,r.y+r.h+178,{steps:8});await page.mouse.up();let after=await tiled();assert.ok(after.brief.h>m.height*.55);assert.ok(after.checkWin.y>before.checkWin.y+150);same({mapPanel:before.mapPanel,console:before.console},{mapPanel:after.mapPanel,console:after.console});
 const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('lab4net-layout-v2')).lab.brief.h);assert.ok(Math.abs(stored*m.height-after.brief.h)<2);await page.reload();same(after,await tiled());
 // Every panel can expand temporarily; geometry and saved layout remain intact.
 await preset('guided');before=await rects();const storage=await page.evaluate(()=>localStorage.getItem('lab4net-layout-v2'));
 for(const id of ['brief','checkWin','mapPanel','console','guideWin']){await page.locator(`#${id} .window-expand`).click();const full=await page.locator('#'+id).boundingBox(),area=await page.locator('main').boundingBox();assert.ok(full.width>area.width-40&&full.height>area.height-40,`${id} expands fully`);assert.equal(await page.evaluate(()=>localStorage.getItem('lab4net-layout-v2')),storage);await page.keyboard.press('Escape');same(before,await rects());}
 await page.locator('#brief .window-heading b').dblclick();assert.ok(await page.locator('main').evaluate(el=>el.classList.contains('panel-expanded')));await page.locator('#brief .window-expand').press('Enter');same(before,await rects());
 await page.locator('#guideClose').click();before=await preset();
 // Four visible relative targets insert the source, close its vacancy, and keep every panel tiled.
 for(const side of ['left','right','top','bottom']){before=await preset();await begin('brief');assert.equal(await page.locator('.dock-target').count(),19);await target('console',side);assert.ok(await page.locator('.dock-target.active').count()===1);assert.match(await page.locator('#layoutDragTip').textContent(),/Place Mission/);assert.equal(await page.locator('.layout-preview-box').count(),4);
  if(side==='left'&&process.env.LAB4NET_SCREENSHOTS){fs.mkdirSync(process.env.LAB4NET_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.LAB4NET_SCREENSHOTS,'docking-targets.png')});}
  await page.mouse.up();after=await tiled();const a=after.brief,b=after.console;if(side==='left')assert.ok(a.x+a.w<=b.x+1);if(side==='right')assert.ok(b.x+b.w<=a.x+1);if(side==='top')assert.ok(a.y+a.h<=b.y+1);if(side==='bottom')assert.ok(b.y+b.h<=a.y+1);assert.ok(after.checkWin.h>before.checkWin.h+100,'tasks fill the vacated mission area');await page.locator('#undoLayout').click();same(before,await tiled());}
 // Full-height mission docking catches the former cap even after a snap.
 await begin('brief');await target('workspace','left');await page.mouse.up();after=await tiled();m=await page.locator('main').boundingBox();assert.ok(after.brief.h>m.height*.9);await page.locator('#undoLayout').click();same(before,await tiled());
 // Missing a target cancels instead of leaving overlapping panels.
 const saved=await page.evaluate(()=>localStorage.getItem('lab4net-layout-v2'));await begin('brief');await page.mouse.move(before.console.x+20,before.console.y+65);await page.mouse.up();same(before,await tiled());assert.equal(await page.evaluate(()=>localStorage.getItem('lab4net-layout-v2')),saved);
 // Accessible panel menu uses the same layout calculation as dragging.
 await page.locator('#brief .window-arrange').click();await page.locator('#arrangeTarget').selectOption('console');await page.locator('[data-place-side="top"]').click();after=await tiled();assert.ok(after.brief.y+after.brief.h<=after.console.y+1);await page.locator('#undoLayout').click();same(before,await tiled());
 // Resize after relative insertion; the affected subtree adjusts without moving unrelated panels.
 await page.locator('#brief .window-arrange').click();await page.locator('#arrangeTarget').selectOption('console');await page.locator('[data-place-side="left"]').click();before=await tiled();r=before.brief;await page.mouse.move(r.x+r.w-2,r.y+r.h/2);await page.mouse.down();await page.mouse.move(r.x+r.w+48,r.y+r.h/2,{steps:6});await page.mouse.up();after=await tiled();assert.ok(after.brief.w>before.brief.w+30);assert.ok(after.console.x>before.console.x+30);same({mapPanel:before.mapPanel,checkWin:before.checkWin},{mapPanel:after.mapPanel,checkWin:after.checkWin});
 if(process.env.LAB4NET_SCREENSHOTS){await page.locator('#brief .window-expand').click();await page.waitForTimeout(300);await page.screenshot({path:path.join(process.env.LAB4NET_SCREENSHOTS,'expanded-mission.png')});await page.keyboard.press('Escape');}
 // A freely overlapped arrangement can return to coordinated docking without a reset.
 before=await preset();await page.keyboard.down('Alt');await begin('brief');await page.mouse.move(before.console.x+before.console.w/2,before.console.y+before.console.h/2);await page.mouse.up();await page.keyboard.up('Alt');
 await begin('brief');await target('console','left');assert.equal(await page.locator('.layout-preview-box').count(),4);await page.mouse.up();await tiled();
 await page.locator('#labs').selectOption('quiz');await page.locator('#practice .window-expand').click();m=await page.locator('main').boundingBox();r=await page.locator('#practice').boundingBox();assert.ok(r.width>m.width-40&&r.height>m.height-40);await page.keyboard.press('Escape');
 for(const [width,height]of [[1366,768],[1024,768]]){await page.setViewportSize({width,height});await page.locator('#labs').selectOption('0');await preset();await begin('brief');await target('workspace','left');await page.mouse.up();after=await tiled();m=await page.locator('main').boundingBox();assert.ok(after.brief.h>m.height*.9);}
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('#brief .window-tools').isVisible(),false);assert.deepEqual(errors,[]);console.log('PASS docking v2: mission exceeds 43% and persists, full-height docking, all panel expansion/restore, double-click/keyboard, visible relative targets with vacancy closure, cancel outside targets, accessible arrangement, subtree resizing, desktop sizes and phone/reduced motion.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
